### PR TITLE
Swampie additions

### PR DESCRIPTION
**Pull request by UndeadZeratul**
@swampyrad I noticed this was sitting in Ted's old repo, are these changes still accurate/desired?

### CODE REVIEW

**Comment by swampyrad** [comment]
Oh, yeah, these were the new ammos I made for my custom weapons. You can put them in. I'll put in their respective weapons into RadTech once it's done.

**Comment by UndeadZeratul** [comment]
Do you see anything that's missing from the changes?

**Comment by swampyrad** [comment]
Nope, looks good to me. That's everything I remember sending to Ted the last time I DM'ed him.

**Comment by UndeadZeratul** [comment]
Cool, all merged into `main`, feel free to give it a test run for your merges into Radtech!

**Pull request merged**
