### PR TITLE
added a 20mm box pickup

### PR DESCRIPTION
**Pull request by Thecrik**
Now if 20mm spawns are enabled instead of a single 20mm grenade replacing an entire rocket box, a box of 10 will spawn. Should make using 20mm a little easier and friendlier to any possible future weapons that use the round.

The original ammo box sprite before being edited was made by zrrion (original zdoom [thread](https://forum.zdoom.org/viewtopic.php?t=35797))

### CODE REVIEW

**Comment by UndeadZeratul** [comment]
I'm sorry for the late response to this, I honestly didn't even see it until now.  Everything looks good to me.  Does Zrrion want credit for their sprites?  Also would it make sense to add a new spawn replacement for the individual 20mm grenades now that the box spawns in their place?

Otherwise this looks good and I can merge it in whenever!

**Comment by Thecrik** [comment]
While the sprites were definitely put up with the intention of being used by others, I'm not sure what level of credit is necessary, as the thread doesn't state. Since they don't state I tend to lean towards crediting them.

As for an individual 20mm spawn, I'm not sure what would be best for it to replace, as it usually doesn't feel like an equal trade. (pistol magazines or some 12ga spawns?)

**Comment by UndeadZeratul** [comment]
That's fair, I was initially thinking of individual rocquettes, but as you point out, that's probably not a fair trade.  It's not something that needs to be done before this is merged, it was mostly a curiosity question.

As for crediting Zrrion, I agree, I'd rather be safe than sorry.  If you'd like you can add them otherwise I'll get to it tomorrow after I merge this in.

**Comment by Thecrik** [comment]
Since I'm unsure exactly where the credits should be placed in relation to the rest of the library, I'll leave it to you.

**Comment by UndeadZeratul** [comment]
Ah, I took a look and it seems nothing so far has any credits associated with them... I can add it to the readme but I won't know who made what that already exists so far...

**Pull request merged**
